name: Secure DevSecOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_package:
    name: BUILD-JOB
    runs-on: ubuntu-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'	  

      - name: BUILD-JOB
        run: npm install

      - name: TEST
        run: echo "code is tested"

      - name: Artifact upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact-1
          path: |
            package*	  
