name: Node.js Parallel Build

on:
  push:
    branches:
      - main
      - master

jobs:

  build:
    name: BUILD-JOB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # Setup Node.js 24
      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Cache Node Modules
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present


  test:
    name: TEST-JOB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # Setup Node.js 24
      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Cache Node Modules
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm test


  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # Setup Node.js 24
      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Cache Node Modules
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install Dependencies
        run: npm install
      - name: deploy
        run: echo "deployment done"
