name: Node.js Parallel Build

on:
  push:
    branches:
      - main
      - master

jobs:

  build:
    name: BUILD-JOB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present


  test:
    name: TEST-JOB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test


  security:
    name: SECURITY-JOB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Security Audit
        run: npm audit --audit-level=high
